version: '3.8'

services:
  grobid:
    image: grobid/grobid:0.8.2
    ports:
      - "8070:8070"
    environment:
      - JAVA_OPTS=-Xmx4g -XX:+UseG1GC
    volumes:
      - grobid_data:/opt/grobid/grobid-home
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  grobid_data:

